# Generated by Django 6.0.2 on 2026-02-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='allowed_radius',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='center',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='center',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
