# Generated by Django 6.0.2 on 2026-02-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
    ]
